### ISSUE TITLE
When there's only one dimension, the All tab doesn't appear

### ISSUE THREAD

**Issue by dgrtwo** [datacamp/tidymetrics#15]
Is this intentional?

Reproducible example. YAML header:

```
---
name: metrics_stock_prices
owner: drob
metrics:
  usd_close:
    title: Closing Price
    description: Close price, in USD, at the end of this time period.
  nb_volume:
    title: Volume
    description: Number of shares traded
dimensions:
  symbol:
    title: Stock
    description: Stock symbol
---
```

Code:

```
library(dplyr)
library(tidymetrics)
library(shinymetrics)
library(tidyquant)
stocks <- tq_get(c("AAPL", "GOOG"))

stocks_summarized <- stocks %>%
  cross_by_dimensions(symbol) %>%
  cross_by_periods(c("day", "week")) %>%
  summarize(nb_volume = sum(volume),
            usd_close = last(close))

m <- create_metrics(stocks_summarized)

preview_metric(m$stock_prices_nb_volume)
```

Result:

![image](https://user-images.githubusercontent.com/994718/79350550-9899c600-7f05-11ea-8b37-28871a019e4a.png)
